/home/lieberum/.conda/envs/minerl/lib/python3.8/site-packages/gym/logger.py:30: UserWarning: [33mWARN: Box bound precision lowered by casting to float32[0m
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
Saving logs and model to /home/lieberum/minerl/run_logs/DynamicsModel/MineRLTreechopVectorObf-v0
Encoder img_shapes: [(64, 64), (31, 31), (15, 15), (7, 7), (3, 3)]

Image sizes for deconv: [(3, 3), (7, 7), (15, 15), (31, 31), (64, 64)]

Loading data of MineRLTreechopVectorObf-v0 from /home/lieberum/minerl/data/numpy_data..

num train samples = 101072 --> 506 train batches
num val samples = 11230
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
Using native 16bit precision.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
Set SLURM handle signals.

  | Name       | Type                 | Params
----------------------------------------------------
0 | VAE        | ConvVAE              | 2.5 M 
1 | base_model | DynamicsBaseModel    | 788 K 
2 | criterion  | MSELoss              | 0     
3 | merge      | MergeFramesWithBatch | 0     
4 | split      | SplitFramesFromBatch | 0     
----------------------------------------------------
3.3 M     Trainable params
0         Non-trainable params
3.3 M     Total params
13.057    Total estimated model params size (MB)
/home/lieberum/.conda/envs/minerl/lib/python3.8/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448278899/work/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
Traceback (most recent call last):
  File "train_DynamicsModel.py", line 86, in <module>
    train_DynamicsModel(**args)
  File "train_DynamicsModel.py", line 66, in train_DynamicsModel
    trainer.fit(model, train_loader, val_loader)
  File "/home/lieberum/.conda/envs/minerl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 460, in fit
    self._run(model)
  File "/home/lieberum/.conda/envs/minerl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 758, in _run
    self.dispatch()
  File "/home/lieberum/.conda/envs/minerl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 799, in dispatch
    self.accelerator.start_training(self)
  File "/home/lieberum/.conda/envs/minerl/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 96, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/lieberum/.conda/envs/minerl/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 144, in start_training
    self._results = trainer.run_stage()
  File "/home/lieberum/.conda/envs/minerl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 809, in run_stage
    return self.run_train()
  File "/home/lieberum/.conda/envs/minerl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 844, in run_train
    self.run_sanity_check(self.lightning_module)
  File "/home/lieberum/.conda/envs/minerl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in run_sanity_check
    self.run_evaluation()
  File "/home/lieberum/.conda/envs/minerl/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 967, in run_evaluation
    output = self.evaluation_loop.evaluation_step(batch, batch_idx, dataloader_idx)
  File "/home/lieberum/.conda/envs/minerl/lib/python3.8/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 174, in evaluation_step
    output = self.trainer.accelerator.validation_step(args)
  File "/home/lieberum/.conda/envs/minerl/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 226, in validation_step
    return self.training_type_plugin.validation_step(*args)
  File "/home/lieberum/.conda/envs/minerl/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/dp.py", line 101, in validation_step
    return self.model(*args, **kwargs)
  File "/home/lieberum/.conda/envs/minerl/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lieberum/.conda/envs/minerl/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/lieberum/.conda/envs/minerl/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/lieberum/.conda/envs/minerl/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/lieberum/.conda/envs/minerl/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/lieberum/.conda/envs/minerl/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/lieberum/.conda/envs/minerl/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lieberum/.conda/envs/minerl/lib/python3.8/site-packages/pytorch_lightning/overrides/data_parallel.py", line 77, in forward
    output = super().forward(*inputs, **kwargs)
  File "/home/lieberum/.conda/envs/minerl/lib/python3.8/site-packages/pytorch_lightning/overrides/base.py", line 57, in forward
    output = self.module.validation_step(*inputs, **kwargs)
  File "/home/lieberum/minerl/research_code/models.py", line 82, in validation_step
    pred_obs, target_obs = self._step(batch)
  File "/home/lieberum/minerl/research_code/models.py", line 65, in _step
    obs = torch.cat([self.VAE.encode_only(pov), vec], dim=2)
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

Validation sanity check: 0it [00:00, ?it/s]Validation sanity check:   0%|          | 0/2 [00:00<?, ?it/s]                                                              srun: error: r31n4: task 0: Exited with exit code 1
